/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Date; 
import java.text.DateFormat; 
import java.text.SimpleDateFormat; 
import javax.swing.JDesktopPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rosyid
 */
public class FormUtama extends javax.swing.JFrame {

    int sttsLogin = 0;
    public FormUtama() {
        initComponents();
        this.setLocationRelativeTo(null);        
        LabelWaktu.setText(getTanggal());
    }
 
    public String usern;
    public String getUsern(){
        return usern;
    }
    public String getTanggal() { 
        DateFormat dateFormat = new SimpleDateFormat("dd/MMM/yyyy"); 
        Date date = new Date(); 
        return dateFormat.format(date);         
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPerpus = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        LabelWaktu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        loginSbg = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MIlogout = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MILapPinjam = new javax.swing.JMenuItem();
        MILapkmbali = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        PanelPerpus.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));

        LabelWaktu.setBackground(new java.awt.Color(255, 255, 255));
        LabelWaktu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelWaktu.setForeground(new java.awt.Color(255, 255, 255));
        LabelWaktu.setText("Waktu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Perpustakaan Jendela Ilmu");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Yogyakarta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(121, 121, 121)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelWaktu)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6))
                    .addComponent(LabelWaktu))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sebagai");

        loginSbg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Petugas Perpus" }));

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser)
                            .addComponent(txtPassword)
                            .addComponent(loginSbg, 0, 155, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loginSbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout PanelPerpusLayout = new javax.swing.GroupLayout(PanelPerpus);
        PanelPerpus.setLayout(PanelPerpusLayout);
        PanelPerpusLayout.setHorizontalGroup(
            PanelPerpusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelPerpusLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        PanelPerpusLayout.setVerticalGroup(
            PanelPerpusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPerpusLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        PanelPerpus.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelPerpus.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MenuFile.setText("File");
        MenuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuFileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuFileMouseEntered(evt);
            }
        });
        MenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileActionPerformed(evt);
            }
        });

        MIlogout.setText("Log Out");
        MIlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIlogoutActionPerformed(evt);
            }
        });
        MenuFile.add(MIlogout);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuFile.add(jMenuItem3);

        jMenuBar1.add(MenuFile);

        jMenu1.setText("Laporan");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu1MouseEntered(evt);
            }
        });

        MILapPinjam.setText("Laporan Peminjaman Buku");
        MILapPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MILapPinjamActionPerformed(evt);
            }
        });
        jMenu1.add(MILapPinjam);

        MILapkmbali.setText("Laporan Pengembalian Buku");
        MILapkmbali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MILapkmbaliActionPerformed(evt);
            }
        });
        jMenu1.add(MILapkmbali);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPerpus)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPerpus)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = txtUser.getText();
        String password = new String (txtPassword.getPassword());

        if(loginSbg.getSelectedIndex()==0)
        {
            try{
            Connection c = KoneksiDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tb_admin WHERE username=? AND pass=?";
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);
            
            ResultSet rs = ps.executeQuery(); 
            
            if(rs.next())
            {
                sttsLogin=1;
                try{
                    
                    PanelPerpus.removeAll();
                        Admin ad = new Admin();
                        ad.setBounds(0, 0, 1200, 659);
                        PanelPerpus.add(ad);
                        ad.datadiri(rs.getString("id_petugas"));
                        ad.setVisible(true);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Username atau Passwoerd Tidak Tepat");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            
        }
        else if(loginSbg.getSelectedIndex()==1)
        {
            sttsLogin=1;
            try{
            Connection c = KoneksiDatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tb_user WHERE username=? AND pass=?";
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);
            
            ResultSet rs = ps.executeQuery(); 
            
            if(rs.next())
            {
                try{
                    PanelPerpus.removeAll();
                    Petugas ptgs = new Petugas();
                    ptgs.setBounds(0, 0, 1200, 659);
                    PanelPerpus.add(ptgs);
                    ptgs.datadiri(rs.getString("id_petugas"));
                    ptgs.setVisible(true);
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Username atau Passwoerd Tidak Tepat");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        
//        usern = txtUser.getText();
//        try{
//                        PanelPerpus.removeAll();
//                        Admin ad = new Admin();
//                        ad.setBounds(0, 0, 1200, 659);
//                        PanelPerpus.add(ad);
//                        ad.setVisible(true);
//                }catch(Exception e){
//                    JOptionPane.showMessageDialog(null, e);
//                }
//        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MIlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIlogoutActionPerformed
        // TODO add your handling code here:
        PanelPerpus.removeAll();
        FormUtama main = new FormUtama();        
        this.setVisible(false);
        main.setVisible(true);
        sttsLogin=0;
    }//GEN-LAST:event_MIlogoutActionPerformed

    private void MenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileActionPerformed

    }//GEN-LAST:event_MenuFileActionPerformed

    private void MenuFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFileMouseClicked

    }//GEN-LAST:event_MenuFileMouseClicked

    private void MenuFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFileMouseEntered
        // TODO add your handling code here:
        if(sttsLogin==0){
                MIlogout.setEnabled(false);
                MILapPinjam.setVisible(false);
            }else{
                MIlogout.setEnabled(true);   
                MILapPinjam.setVisible(true);
            }
    }//GEN-LAST:event_MenuFileMouseEntered

    private void jMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseEntered
        // TODO add your handling code here:
        if(sttsLogin==0){
                MILapPinjam.setVisible(false);
                MILapkmbali.setVisible(false);
            }else{ 
                MILapPinjam.setVisible(true);
                MILapkmbali.setVisible(true);
            }
    }//GEN-LAST:event_jMenu1MouseEntered

    private void MILapPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MILapPinjamActionPerformed
        // TODO add your handling code here:
        try{
            Connection conex = KoneksiDatabase.getkoneksi();
            String report = "/home/rosyid/NetBeansProjects/Perpus/src/report/Lpeminjaman.jrxml";
            JasperReport JASP_REP = JasperCompileManager.compileReport(report);
            JasperPrint JASP_PRNT = JasperFillManager.fillReport(JASP_REP, null, conex);
            JasperViewer.viewReport(JASP_PRNT);
        }catch(Exception X)
        {
            JOptionPane.showMessageDialog(null, X);
        }
    }//GEN-LAST:event_MILapPinjamActionPerformed

    private void MILapkmbaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MILapkmbaliActionPerformed
        // TODO add your handling code here:
        try{
            Connection conex = KoneksiDatabase.getkoneksi();
            String report = "/home/rosyid/NetBeansProjects/Perpus/src/report/Lpengembalian.jrxml";
            JasperReport JASP_REP = JasperCompileManager.compileReport(report);
            JasperPrint JASP_PRNT = JasperFillManager.fillReport(JASP_REP, null, conex);
            JasperViewer.viewReport(JASP_PRNT);
        }catch(Exception X)
        {
            JOptionPane.showMessageDialog(null, X);
        }
    }//GEN-LAST:event_MILapkmbaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelWaktu;
    private javax.swing.JMenuItem MILapPinjam;
    private javax.swing.JMenuItem MILapkmbali;
    private javax.swing.JMenuItem MIlogout;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JDesktopPane PanelPerpus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox loginSbg;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
